export { registerPages } from './host'
export { goto } from './goto'
export { ficsLink } from './link'
export { renderMeta } from './meta'
export type { FiCsLink, FiCsRouter } from './namespaces'
export { dynamicPaths, queries } from './params'
export { registerRoutes } from './registry'
export { ficsRouter } from './router'
