export { goto } from './goto'
export { ficsLink } from './link'
export type { FiCsLink, FiCsRouter } from './namespaces'
export { dynamicPaths, queries } from './params'
export { ficsRouter } from './router'
