export const BASE_DIR = './pages' as const
export const COMMENT = '// This file is auto-generated by fics-routes. Please do not edit.' as const

export const config = {
  DIR: 'src/pages',
  MIDDLEWARE: 'middleware.gen.ts',
  OUTPUT: 'src/routes.gen.ts',
  RPC_CLIENT: 'rpc.client.gen.ts',
  RPC_SERVER: 'rpc.server.gen.ts'
} as const

export const ENTRIES_DIR = '.fics/routing-entries' as const

export const exitCodes = { SUCCESS: 0, FAILURE: 1 } as const

export const EXTENSIONS = ['.js', '.ts'] as const

export const fileNames = {
  LAYOUT: '+layout',
  MIDDLEWARE: '+middleware',
  PAGE: '+page',
  PAGE_SERVER: '+page.server',
  REDIRECT: '+redirect',
  RPC: '+rpc',
  SPA: '+spa',
  SPA_CONFIG: '+spa.config',
  statuses: {
    FORBIDDEN: '+403',
    INTERNAL_SERVER_ERROR: '+500',
    NOT_FOUND: '+404',
    UNAUTHORIZED: '+401'
  }
} as const

export const MODULE_EXT_REGEX: RegExp = /\.(?:tsx?|jsx?|mts|mjs|cts|cjs)$/

export const prefixes = { LAYOUT: '__layout', REDIRECT: '__redirect', STATUS: '__status' } as const

export const routerImport = (path: string = '') =>
  `'ficsjs/router${path ? `/${path}` : ''}'` as const

export const segments = {
  CATCH_ALL: /^\[\.\.\.([^[\].]+)\]$/,
  DYNAMIC: /^\[([^[\].]+)\]$/
} as const
