export const config = {
  ALIAS: '@fics',
  ENTRIES: 'entries',
  IMPORT_BASE: './pages',
  CLIENT: 'client.ts',
  OUTPUT: '.fics/routing',
  SCANNED_DIR: 'src/pages',
  SERVER: 'server.ts',
  TOOL_NAME: 'fics-routing'
} as const

export const COMMENT =
  `// This file is auto-generated by ${config.TOOL_NAME}. Please do not edit.` as const

export const DEBOUNCE_DELAY_MS = 50 as const

export const exitCodes = { SUCCESS: 0, FAILURE: 1 } as const

export const EXTENSIONS = ['.js', '.ts'] as const

export const fileNames = {
  LAYOUT: '+layout',
  MIDDLEWARE: '+middleware',
  PAGE: '+page',
  PAGE_SERVER: '+page.server',
  REDIRECT: '+redirect',
  RPC: '+rpc',
  SPA: '+spa',
  SPA_CONFIG: '+spa.config',
  statuses: {
    FORBIDDEN: '+403',
    INTERNAL_SERVER_ERROR: '+500',
    NOT_FOUND: '+404',
    UNAUTHORIZED: '+401'
  }
} as const

export const metaExports = {
  INLINE: /\bexport\s+(?:const|let|var|function|async\s+function)\s+meta\b/,
  BLOCK: /\bexport\s*\{[^}]*\bmeta\b/
} as const

export const MODULE_EXT_REGEX: RegExp = /\.(?:tsx?|jsx?|mts|mjs|cts|cjs)$/

export const prefixes = {
  LAYOUT: '__layout',
  MIDDLEWARE: '__middleware',
  REDIRECT: '__redirect',
  STATUS: '__status'
} as const

export const routerImport = (path: string = '') =>
  `'ficsjs/router${path ? `/${path}` : ''}'` as const

export const segments = {
  CATCH_ALL: /^\[\.\.\.([^[\].]+)\]$/,
  DYNAMIC: /^\[([^[\].]+)\]$/
} as const
