import { RPC_BASE_PATH } from './../constants'
import type { Routing, Rpc, TypeNode } from './../types'
import { fileNames, routerImport, segments } from './constants'
import { buildRoute, getFiles, indent, joinLines, resolveOptions } from './helpers'

const newNode = (): TypeNode => ({ children: new Map() }),
  renderType = ({ alias, children, dynamic }: TypeNode): string => {
    const operands: string[] = []

    if (alias) operands.push(`typeof ${alias}`)

    if (children.size > 0) {
      const members: string[] = [...children.entries()].map(
        ([segment, child]) => `${JSON.stringify(segment)}: ${renderType(child)}`
      )
      operands.push(`{ ${members.join('; ')} }`)
    }

    if (dynamic) operands.push(`((${dynamic.name}: string) => ${renderType(dynamic.node)})`)

    return operands.length > 0 ? operands.join(' & ') : 'Record<never, never>'
  }

export const generateRpcs = ({
  filePaths,
  options,
  basePath
}: {
  filePaths: string[]
  options?: Routing.Options.Generate
  basePath?: string
}): Rpc.Generated | null => {
  const { baseDir, extensions } = resolveOptions(options),
    rpcs: Routing.ServerEntries = getFiles({
      filePaths,
      extensions,
      expectedType: fileNames.SERVER,
      baseDir
    })

  if (rpcs.length === 0) return null

  const aliases: string[] = rpcs.map((_, index) => `rpc${index}`),
    root: TypeNode = newNode(),
    manifests: string[] = []

  for (const [index, { dirs }] of rpcs.entries()) {
    const alias: string = aliases[index]

    manifests.push(`{ prefix: ${JSON.stringify(buildRoute(dirs))}, module: ${alias} }`)

    let node: TypeNode = root
    for (const segment of dirs) {
      if (segments.CATCH_ALL.test(segment))
        throw new Error(
          `The catch-all segment "${segment}" is not supported for RPC procedures... `
        )

      const dynamic: RegExpMatchArray | null = segment.match(segments.DYNAMIC)
      if (dynamic) {
        const paramName: string = dynamic[1]

        if (node.dynamic && node.dynamic.name !== paramName)
          throw new Error(
            `The dynamic segment "[${paramName}]" conflicts with the existing dynamic segment "[${node.dynamic.name}]" at the same level...`
          )

        node.dynamic ??= { name: paramName, node: newNode() }
        node = node.dynamic.node
      } else {
        if (!node.children.has(segment)) node.children.set(segment, newNode())
        node = node.children.get(segment)!
      }
    }

    node.alias = alias
  }

  const note: string = `// This file is auto-generated by fics-routes. Please do not edit.`,
    importModules = (type: 'client' | 'server'): string =>
      joinLines(
        rpcs.map(
          ({ specifier }, index) =>
            `import ${type === 'client' ? 'type ' : ''}* as ${aliases[index]} from '${specifier}'`
        )
      ),
    client = joinLines([
      note,
      `import { createRpcClient } from ${routerImport()}`,
      importModules('client'),
      '',
      `export const api = createRpcClient<${renderType(root)}>('${basePath ?? RPC_BASE_PATH}')`,
      ''
    ]),
    server = joinLines([
      note,
      `import ${routerImport('server-only')}`,
      importModules('server'),
      '',
      'export const rpcRouter = [',
      joinLines(
        manifests.map(entry => `${indent()}${entry}`),
        true
      ),
      ']',
      ''
    ])

  return { client, server }
}
